Clarify partial method for joins
apostrophecms/apostrophe-documentation pull request #340
Opened 2021-02-04 20:10 UTC by notebk

I saw this solution answered by @boutell in SO. I couldn't understand this part of the docs, so adding in a bit of context for how to use the partial method with joins.

2021-02-11 21:23 UTC, abea requested changes
Thanks for this contribution! The section after your addition explains what the `partial` option is, so please move your addition after that next code block and directly before the "It's important to note..." paragraph.

2021-02-11 21:23 UTC, abea commented on docs/advanced-topics/advanced-pieces-topics/adding-columns.md
> +To display the title or another field of a join in a column, include the `partial` method in the `addColumns` options:
How about "the title or another field from a join" (note the "from")?

2021-02-11 21:23 UTC, abea commented on docs/advanced-topics/advanced-pieces-topics/adding-columns.md
> +  //Other configuration options, then...
Add a space before "Other"

2021-02-18 19:26 UTC, notebk commented
Thanks for the feedback! I just added in the proposed changes

2021-02-19 14:59 UTC, abea commented
Thanks, @notebk!

2021-02-19 14:59 UTC, abea approved these changes

2021-02-19 14:59 UTC, merged